### ISSUE TITLE
working successfully on the MAiX GO?

### ISSUE THREAD

**Issue by pdp7** [laanwj/k210-sdk-stuff#7]
I just asked on Twitter but got the response that it is not working:
https://twitter.com/carlosedp/status/1245461518587777026

but that Damien might have some solution:
https://twitter.com/carlosedp/status/1245462016346783746

Thanks for your efforts.  I'm interested to help out.

**Comment by laanwj** [comment]
FWIW it was working for me, the Maix Go is the only Maix device I have and use for development. The `esptun` intentionally does no dynamic allocation of any kind to optimize memory usage.

However, even with that I didn't get further than pinging due to memory fragmentation issues with busybox. I guess it is a fragile balance of kernel/busybox features that makes it work for me.

**Comment by pdp7** [comment]
Thanks for the insights
